# .github/workflows/keep-alive.yml

name: HuggingFace Space 

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  ping_spaces: # Job name可以保持不变或修改
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to Multiple Spaces
        run: |
          echo "Pinging all my Spaces..."
          # --- 在下面添加你要保持活跃的 Space URL 列表 ---
          curl -s "https://cq1026-2-5voapi.hf.space/"
          curl -s "https://cq1026-cskaixiang.hf.space/"
          curl -s "https://cq1026-jini.hf.space/"
          # ----------------------------------------------------
          echo "All Spaces have been pinged."
